export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST';
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL';

export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT';
export const RESTAURANT_UPDATE = 'RESTAURANT_UPDATE';

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST';
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS';
export const RESTAURANT_REGISTER_FAIL = 'RESTAURANT_REGISTER_FAIL';

export const GET_RESTAURANT_REQUEST = 'GET_RESTAURANT_REQUEST';
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS';
export const GET_RESTAURANT_FAIL = 'GET_RESTAURANT_FAIL';

export const UPDATE_RESTAURANT_IMAGE_REQUEST = 'UPDATE_RESTAURANT_IMAGE_REQUEST';
export const UPDATE_RESTAURANT_IMAGE_SUCCESS = 'UPDATE_RESTAURANT_IMAGE_SUCCESS';
export const UPDATE_RESTAURANT_IMAGE_FAIL = 'UPDATE_RESTAURANT_IMAGE_FAIL';
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET';

export const UPDATE_RESTAURANT_REQUEST = 'UPDATE_RESTAURANT_REQUEST';
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAIL = 'UPDATE_RESTAURANT_FAIL';
export const UPDATE_RESTAURANT_RESET = 'UPDATE_RESTAURANT_RESET';

// category
export const CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

// statistics
export const GET_STATISTICS_REQUEST = 'GET_STATISTICS_REQUEST';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export const GET_STATISTICS_FAIL = 'GET_STATISTICS_FAIL';

// dish
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAIL = 'DISHES_FAIL';

export const DISH_LIST_ADD = 'DISH_LIST_ADD';
export const DISH_LIST_REMOVE = 'DISH_LIST_REMOVE';

export const GET_DISHES_REQUEST = 'GET_DISHES_REQUEST';
export const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';

export const ADD_DISH_REQUEST = 'ADD_DISH_REQUEST';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';

export const UPDATE_DISH_REQUEST = 'UPDATE_DISH_REQUEST';
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS';

export const DISH_FORM_FAIL = 'DISH_FORM_FAIL';
export const DISH_FORM_RESET = 'DISH_FORM_RESET';

// employees
export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING';
export const EMPLOYEES_FAIL = 'EMPLOYEES_FAIL';

export const EMPLOYEE_LIST_ADD = 'EMPLOYEE_LIST_ADD';
export const EMPLOYEE_LIST_REMOVE = 'EMPLOYEE_LIST_REMOVE';

export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';

export const EMPLOYEE_FORM_FAIL = 'EMPLOYEE_FORM_FAIL';
export const EMPLOYEE_FORM_RESET = 'EMPLOYEE_FORM_RESET';

// branch
export const BRANCHES_LOADING = 'BRANCHES_LOADING';
export const BRANCHES_FAIL = 'BRANCHES_FAIL';

export const GET_BRANCH_REQUEST = 'GET_BRANCH_REQUEST';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';

export const ADD_BRANCH_REQUEST = 'ADD_BRANCH_REQUEST';
export const ADD_BRANCH_SUCCESS = 'ADD_BRANCH_SUCCESS';

export const BRANCH_LIST_ADD = 'BRANCH_LIST_ADD';
export const BRANCH_LIST_REMOVE = 'BRANCH_LIST_REMOVE';

export const UPDATE_BRANCH_REQUEST = 'UPDATE_BRANCH_REQUEST';
export const UPDATE_BRANCH_SUCCESS = 'UPDATE_BRANCH_SUCCESS';

export const BRANCH_FORM_FAIL = 'BRANCH_FORM_FAIL';
export const BRANCH_FORM_RESET = 'BRANCH_FORM_RESET';