export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST';
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL';

export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT';

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST';
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS';
export const RESTAURANT_REGISTER_FAIL = 'RESTAURANT_REGISTER_FAIL';

export const GET_RESTAURANT_REQUEST = 'GET_RESTAURANT_REQUEST';
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS';
export const GET_RESTAURANT_FAIL = 'GET_RESTAURANT_FAIL';

export const UPDATE_RESTAURANT_IMAGE_REQUEST = 'UPDATE_RESTAURANT_IMAGE_REQUEST';
export const UPDATE_RESTAURANT_IMAGE_SUCCESS = 'UPDATE_RESTAURANT_IMAGE_SUCCESS';
export const UPDATE_RESTAURANT_IMAGE_FAIL = 'UPDATE_RESTAURANT_IMAGE_FAIL';
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET';

export const RESTAURANT_UPDATE = 'RESTAURANT_UPDATE';

export const UPDATE_RESTAURANT_REQUEST = 'UPDATE_RESTAURANT_REQUEST';
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAIL = 'UPDATE_RESTAURANT_FAIL';
export const UPDATE_RESTAURANT_RESET = 'UPDATE_RESTAURANT_RESET';

// category
export const CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

// dish
export const GET_DISHES_REQUEST = 'GET_DISHES_REQUEST';
export const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';
export const GET_DISHES_FAIL = 'GET_DISHES_FAIL';