export const RESET_ERRORS = 'RESET_ERRORS';
export const HOME_SCREEN = 'Home';
export const LOGIN_SCREEN = 'Login';
export const EMP_LOGIN_SCREEN = 'EmpLogin';

export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL';
export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT';

export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS';
export const EMPLOYEE_LOGIN_FAIL = 'EMPLOYEE_LOGIN_FAIL';
export const EMPLOYEE_LOGOUT = 'EMPLOYEE_LOGOUT';

export const SET_ORDERS = 'SET_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER';
