export const HOME_SCREEN = "Home";
export const LOGIN_SCREEN = "Login";

export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL';
export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT';